# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9db2c255ffad79609bf9d66dd76cb86ae60f7e6c8d74a294be103014434d7671c2aa755eb6ed02327d7647ab1f9721149456149817774fbc4cf38e4f1e72f43c

test:
  secret_key_base: 359d301ba63b89a053bcf5ef0cf06b861082c61c10295ea83769b831208e47afaebe08bca5d40eba17394aac70b6d20a7178e00409b0a80ad1a44cdead7dc3f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
